Base
FriederikeM/To-Do-App pull request #1
Opened 2021-04-03 14:43 UTC by FriederikeM

- Create new to do
- Change status
- Delete to do
- Edit name

2021-04-05 10:33 UTC, hugh-burgess commented on src/App.css
> +  box-shadow: 13px 13px 20px #cbced1, -13px -13px 20px #ffffff;
skeuomorphism ftw!

2021-04-05 10:36 UTC, hugh-burgess commented on src/components/AddToDo.css
> +  transition: box-shadow 200ms ease-in-out;
niiiice

2021-04-05 10:37 UTC, hugh-burgess commented on src/components/ToDo.css
> +  transition-delay: 0.2s;
interesting...

2021-04-05 10:38 UTC, hugh-burgess approved these changes
LGTM!

2021-04-06 09:50 UTC, namirsab requested changes
Hey @FriederikeM !
Really cool, I loved the animations.

I have some small requests, mostly naming and some changes related to the way you deal with the filters. Please take a look and feel free to ask if something is not clear.

2021-04-06 09:50 UTC, namirsab commented on src/App.css
> +header {
Maybe I'd add a class here instead of styling the element directly. Same for the others.

2021-04-06 09:50 UTC, namirsab commented on src/components/ToDoList.js
> +  handleNameChange,
I'd be consistent with the naming:
`onToggleStatus`
`onDeleteTodo`
 and then you have `handleNameChange`

I'd rename that one to `onNameChanged` or something similar to be consistent with the rest of the props

2021-04-06 09:50 UTC, namirsab commented on src/components/ToDo.js
> +  handleNameChange,
Let's be consistent with the naming, as mentioned before

2021-04-06 09:50 UTC, namirsab commented on src/components/ToDo.js
> +  const classForStatus = isDone ? "toDo--done" : "toDo--pending";
Really cool the way you are handling your animations! 🥳

2021-04-06 09:50 UTC, namirsab commented on src/App.js
> +        <FilterToDos setFilterType={setFilterType} filterType={filterType} />
The `FilterToDos` component is receiving directly the `setFilterType`function that's part of the state.

What you should do is to setup some props: `onChangeFilterType` and handle that event here in the `App.js`
component, which would the one calling the `setFilterType` function.

That way, everything that deals with the state stays in the `App` component, which is the one that creates and manages the state.

2021-04-06 09:50 UTC, namirsab commented on src/App.js
> +        <FilterToDos setFilterType={setFilterType} filterType={filterType} />
```js
function handleChangeFilterType(selectedFilterType) {
    setFilterType(selectedFilterType)
}


<FilterTodos onChangeFilterType={handleChangeFilterType} filterType={filterType} />
```

2021-04-06 09:50 UTC, namirsab commented on src/components/FilterToDos.js
> +  function handleAllFilterClick() {
The logic of these `handleAllFilterClick`and the other 2 (for Done and ToDo) should be done in the `App` component

2021-04-06 09:50 UTC, namirsab commented on src/components/ToDo.js
> +    let isDone = false;
This might be confusing with the `isDone` of the todo. Let's find a better name, like `changingNameIsDone`

2021-04-06 09:50 UTC, namirsab commented on src/App.js
> +      const newTodoName = toDos.map((toDo) => {
This shouldn't be `newTodoName` but `newTodos`

2021-04-11 17:32 UTC, merged